### ISSUE TITLE
Breaking changes should bump a version

### ISSUE THREAD

**Issue by dchem** [status-im/nim-web3#26]
**Commit**: 4590f21d5d47122f5d2376d635798b37ef057293

**Observed**:

`nimble install web3` pulls 0.0.1, and any previously working code with it was broken when `subscribe` proc signature was changed here:

https://github.com/status-im/nim-web3/commit/4590f21d5d47122f5d2376d635798b37ef057293#diff-4031b3eb3ea9303bd2da5a703b39026aL106

**Desired**:

1. Please bump the version if there are any breaking changes.

**Comment by zah** [comment]
Hey, I didn't realize someone is already using our code. That's pretty cool and your complaint is perfectly right - I apologise for the silent breaking change. 

Having that said, please be aware that we don't consider the API of the library stable yet. It's still being expanded and developed on a need-to-use basis and the primary objective is to accommodate the needs of the Nimbus project. Hopefully, in the process we'll gradually arrive at a stable API that we can commit to support without further breaking changes.

What is your use case btw?

**Comment by dchem** [comment]
Thank you for responding so quickly, and thank you for your work on this package! We're working on a non-custodial exchange and we're writing a lot of services in nim.

**Comment by dchem** [comment]
> Having that said, please be aware that we don't consider the API of the library stable yet. It's still being expanded and developed on a need-to-use basis and the primary objective is to accommodate the needs of the Nimbus project. Hopefully, in the process we'll gradually arrive at a stable API that we can commit to support without further breaking changes.

Yes absolutely. We understand. Thank you for working on this package.
