### ISSUE TITLE
feat: Implement EIP-155 (simple replay attack protection)

### ISSUE THREAD

**Issue by rymnc** [status-im/nim-web3#79]
[EIP-155](https://eips.ethereum.org/EIPS/eip-155) requires the `chainId` to be set within the raw tx data, ref: https://github.com/status-im/nim-web3/blob/4c377e6e298ff5391c3f33372d1be0ce340f23ab/web3.nim#L574-L594

This can be worked around by manually constructing the raw tx data, and including the `chainId`

**Comment by jangko** [comment]
fixed by #105, closing
